### ISSUE TITLE
Allow for optional file extensions

### ISSUE THREAD

**Issue by jarinudom** [causes/haml-lint#61]
haml-lint seems to use [Utils#haml_file?](https://github.com/causes/haml-lint/blob/master/lib/haml_lint/utils.rb#L85) to determine whether or not it should process a file. I'm using a kind of rickety asset pipeline preprocessor that requires a `.ractivehaml` extension to process the file via haml and then Ractive. The files are valid haml, but I can't rename them to `.ractive.haml` or anything like that because of some special processing that is a little different than the standard `haml` preprocessor. Any chance it would be possible to add a setting to `.haml-lint.yml` to allow additional file extensions?

**Comment by sds** [comment]
Hey @jarinudom,

Adding a configuration option to support arbitrary extensions seems a bit much, but I do see the value in letting `haml-lint` lint files with arbitrary extensions if they are explicitly listed on the command-line.

So if you write `haml-lint **/*.ractivehaml` (zsh) or `haml-lint *.ractivehaml */*.ractivehaml` (bash), you should get the behavior you want as of 6dd36da1f7469b0eea52caccb414fa8fb7640af8.

**Comment by jarinudom** [comment]
Thank you very much! Now I just need to look up how to pass options to Syntastic and I will be golden. :)
