### ISSUE TITLE
Rubocop-like JSON output

### ISSUE THREAD

**Issue by skateman** [causes/haml-lint#62]
Hi!

I would like ask that are you planning to add an optional rubocop-like json output format?
We have a [bot](https://github.com/ManageIQ/miq_bot), which checks pull requests with rubocop.
I would like to add support for the `haml` files with haml-lint, but I need JSON as output.

Thanks!

**Comment by sds** [comment]
Hey @skateman,

No plans, but would happily accept a pull request!

**Comment by skateman** [comment]
That's what i wanted to hear ;) I'm on it!

**Comment by sds** [comment]
Implemented by #63
